# Face Detector (work in progress)
### Testing face detector using "face_angles.jpg"

In [78]:
# getting image path
# try with flowers.jpg as well (doesn't have any faces)
current = %pwd
from pathlib import Path
path = Path(current)
imagePath = str(path.parent.absolute())
image_name = "face_angles.jpg"
imagePath += '\\' + image_name
imagePath

'c:\\Users\\brian\\Desktop\\PYUM\\P-YUM\\face_angles.jpg'

In [79]:
cascPath = "haarcascade_frontalface_default.xml"

In [80]:
import cv2

In [81]:
# Create the haar cascade
faceCascade = cv2.CascadeClassifier(cascPath)

# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect faces in the image
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
)

In [82]:
print(image)

[[[  0   8   0]
  [  0   4   0]
  [  0   4   0]
  ...
  [  0  11   0]
  [  0  11   0]
  [  0  18   0]]

 [[209 223 212]
  [205 219 208]
  [205 219 208]
  ...
  [ 69  94  66]
  [ 61  86  60]
  [ 77 102  74]]

 [[ 43  62  53]
  [ 39  58  49]
  [ 39  58  49]
  ...
  [ 65  93  63]
  [ 57  85  56]
  [ 73 101  71]]

 ...

 [[182 181 177]
  [155 154 150]
  [134 133 129]
  ...
  [ 69  63  52]
  [ 66  60  49]
  [ 68  62  51]]

 [[203 202 198]
  [195 194 190]
  [203 202 198]
  ...
  [187 182 173]
  [190 185 176]
  [196 191 182]]

 [[  5   4   0]
  [  2   1   0]
  [  2   1   0]
  ...
  [  9   4   0]
  [  9   4   0]
  [ 16  11   2]]]


In [83]:
print ("Found {0} faces!".format(len(faces)))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)


Found 9 faces!


In [84]:
# runs reasonably well
# notice how it doesn't really work on faces that are turned 90 degrees.

cv2.imshow("Faces found", image)
cv2.waitKey(0)


-1

# Face As A Percentage of the Video

In [12]:
# first, get the path of the video in question
# getting video path
current = %pwd
from pathlib import Path
path = Path(current)
filename = str(path.parent.absolute())
video_name = "Binging with Babish_ Patrick's Briefcase from SpongeBob SquarePants.mp4"
filename += '\\' + video_name
filename

"c:\\Users\\brian\\Desktop\\PYUM\\P-YUM\\Binging with Babish_ Patrick's Briefcase from SpongeBob SquarePants.mp4"

In [13]:
import cv2
import numpy as np

In [90]:
def face_detector(image):
    cascPath = "haarcascade_frontalface_default.xml"

    # Create the haar cascade
    faceCascade = cv2.CascadeClassifier(cascPath)

    # Read the image
    # image = cv2.imread(image)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detect faces in the image
    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.3,
        minNeighbors=5,
        minSize=(30, 30),
        flags = cv2.CASCADE_SCALE_IMAGE
    )

    for (x, y, w, h) in faces:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

    if len(faces) >= 1:
        cv2.imshow("Faces found", image)
        cv2.waitKey(0)


    # if it detects at least one face, return true
    # it doesn't have to be the host itself
    if len(faces) >= 1:
        return True
    
    return False

In [91]:
# input: the video file
# output: length of video file in seconds

def find_video_length(video):

    fps = video.get(cv2.CAP_PROP_FPS)
    frame_count = video.get(cv2.CAP_PROP_FRAME_COUNT)

    return frame_count / fps, fps


In [92]:
def face_percentage(filename):

    # person_counter counts number of frames person was in shot
    person_counter = 0
    # no_person_counter counts number of frames where person is not in shot
    no_person_counter = 0

    my_video = cv2.VideoCapture(filename)
    if (my_video.isOpened() == False):
        print("Error opening video stream or file")

    video_length, video_fps = find_video_length(my_video)

    nth_frame = video_fps // 2
    frame_counter = 0

    while (my_video.isOpened()):
        
        ret, frame = my_video.read()
        if frame_counter % nth_frame == 0:

            # Capture frame-by-frame
            if ret == True:
                if face_detector(frame):

                    print(frame_counter / video_fps)
                    person_counter += 1
                else:
                    no_person_counter += 1
            else:
                break

        if ret == False:
            break

        frame_counter += 1

    return (person_counter * 100) / (no_person_counter + person_counter)




In [93]:
filename

"c:\\Users\\brian\\Desktop\\PYUM\\P-YUM\\Binging with Babish_ Patrick's Briefcase from SpongeBob SquarePants.mp4"

In [94]:
face_percentage(filename)

8.258249999999999
8.717041666666667
13.763749999999998
14.222541666666666
14.681333333333333
15.140125
40.83245833333333
54.59620833333333
67.90116666666667
83.95887499999999
89.92316666666666
90.84075
96.80504166666665
101.39295833333333
101.85175
106.43966666666665
107.81604166666666
108.27483333333332
108.73362499999999
113.78033333333333
115.15670833333333
117.45066666666666
117.90945833333332
119.74462499999998
128.46166666666664
139.93145833333332
143.143


KeyboardInterrupt: 